### ISSUE TITLE
minimum number of characters for labels in 'group'

### ISSUE THREAD

**Issue by mnodale** [shug0131/eudraCT#30]
Sorry, writing on behalf of Rachel, so I am not providing an example.
Today we discovered that the names of each treatment arm need to be at least 4 characters long.
News to me. The help page doesn't say anything about it, so I reckon it's some weird dependency & not an intended design feature.
Worth adding to the help page perhaps. "SoC" for instance won't work. Nor cute stuff like "RTX" & "AZA".
Easily circumvented by choosing long treatment labels. 

I will make up an example and forward on.

**Comment by mnodale** [comment]
You seem to know about it already, so thanks for adding the warning.
Additional help: amend help file, adding min number of char for group names is 4! 

PS I learnt today how to look up past issues, so I won't post something known again!

**Comment by shug0131** [comment]
See issue #2
