### ISSUE TITLE
EutctID Version Error

### ISSUE THREAD

**Issue by mariavonk** [shug0131/eudraCT#7]
I'm trying to use the SAS version of your scripts to upload AEs into the EudraCT database. But I always get a version error when I try to upload the XML file, because the code "100000167503" for "Product Issue" is version 3 and all the other meddra Codes are currently version 22 (see the attached screenshot). If I change the version number to 3 or 22 (or with 19 or 20) in the simpleToEudraCT.xslt-file I always get an error, because either the code 100000167503 or the other codes cause an error. I don't see option to change the version based on the meddra code and I don't have any experience with xlst files. Is it possible to change the code so that the version in the xml file is changed based on a "conversion file"? My last option would be to manually change the version number for all Product Issues to 3 but maybe there is an option to avoid that.

Still a big thanks for creating these scripts, they saved me a lot of time and trouble!

![grafik](https://user-images.githubusercontent.com/60782978/74032726-fc0ef100-49b4-11ea-8e34-1c2072287ece.png)

**Comment by shug0131** [comment]
Maria 

Thanks for picking up this problem. Maybe Product Issue is so rare as a SOC that you're the first to encounter it. 

I think that you or we will have to find a way to map each SOC term to the correct version. This is "documented" obscurely  https://spor.ema.europa.eu/rmswi/#/lists/100000000006/terms/100000167503.

I could do this by changing the xslt file, but not for a week or so. So can you workaround this by editing your xml output to have  (in pseudo-code) "if( code= 100000167503 ) version->3 " ?

Feel free to email me via the address on  the website.

thanks Simon

**Comment by shug0131** [comment]
Issue is patched with a conditional statement in the xslt file
